products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('bundles/', views.BundleListView.as_view(), name='bundle-list'),
    path('bundles/create/', views.BundleCreateView.as_view(), name='bundle-create'),
    path('bundles/<int:bundle_id>/', views.BundleDetailView.as_view(), name='bundle-detail'),
    path('bundles/<int:bundle_id>/update/', views.BundleUpdateView.as_view(), name='bundle-update'),
    path('bundles/<int:bundle_id>/delete/', views.BundleDeleteView.as_view(), name='bundle-delete'),

    path('bundles/<int:bundle_id>/products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<int:product_id>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/<int:product_id>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:product_id>/', views.ProductDetailView.as_view(), name='product-detail'),
    # path('bundles/create/', views.BundleListView.as_view(), name='bundle-create'),
    # path('bundles/<int:bundle_id>/update/', views.BundleListView.as_view(), name='bundle-update'),
    # path('bundles/<int:bundle_id>/delete/', views.BundleListView.as_view(), name='bundle-delete'),
]

project_3d/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from common import views as common_views

urlpatterns = [
    path('', common_views.redirect_home, name='root'),
    path('home/', common_views.HomeView.as_view(), name='home'),
    path('documentation/', common_views.DocumentationView.as_view(), name='documentation'),

    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('products.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
import os

from django.db import models

from authentication.models import User


def get_product_3d_asset_path(instance, filename):
    return os.path.join('bundles', str(instance.bundle.pk), 'assets', filename)


def get_product_image_path(instance, filename):
    return os.path.join('bundles', str(instance.bundle.pk), 'images', filename)


class Bundle(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, related_name='bundles', on_delete=models.CASCADE)

    class Meta:
        db_table = 'bundles'

    def __str__(self):
        return self.name


class Product(models.Model):
    bundle = models.ForeignKey(Bundle, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_product_image_path, blank=True, null=True)
    asset = models.FileField(
        upload_to=get_product_3d_asset_path,
        blank=True,
        null=True,
        max_length=126,
        verbose_name='3D assets',
    )

    class Meta:
        db_table = 'products'
        constraints = [
            models.UniqueConstraint(
                fields=['bundle', 'name'],
                name='unique_bundle_product',
            )
        ]

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from products.models import Product, Bundle


class ProductCreateForm(forms.ModelForm):

    def __init__(self, my_context=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = my_context

    class Meta:
        model = Product
        fields = ('name', 'image', 'asset')

    def clean(self):
        bundle = Bundle.objects.filter(id=self.context['bundle_id'], user=self.context['user']).first()
        if bundle is None:
            raise forms.ValidationError(f"Bundle {self.context['bundle_id']} does not belong you!")
        return {**self.cleaned_data, 'bundle': bundle}

    def save(self, commit=True):
        self.instance.bundle = self.cleaned_data['bundle']
        return super(ProductCreateForm, self).save()


class ProductUpdateForm(forms.ModelForm):

    def __init__(self, my_context=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = my_context

    class Meta:
        model = Product
        fields = ('name', 'image', 'asset')

    def clean(self):
        product = Product.objects.filter(id=self.instance.id, bundle__user=self.context['user']).first()
        if product is None:
            raise forms.ValidationError(f"Product does not belong you!")
        return self.cleaned_data


class BundleCreateForm(forms.ModelForm):

    def __init__(self, my_context=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = my_context

    class Meta:
        model = Bundle
        fields = ('name',)

    def save(self, commit=True):
        self.instance.user = self.context['user']
        return super(BundleCreateForm, self).save()


class BundleUpdateForm(forms.ModelForm):

    def __init__(self, my_context=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.context = my_context

    class Meta:
        model = Bundle
        fields = ('name',)

    def clean(self):
        bundle = Bundle.objects.filter(id=self.instance.id, user=self.context['user']).first()
        if bundle is None:
            raise forms.ValidationError(f"Bundle does not belong you!")
        return self.cleaned_data

products/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectTemplateResponseMixin, BaseListView

from products.filters import BundleFilter
from products.forms import ProductCreateForm, ProductUpdateForm, BundleUpdateForm, BundleCreateForm
from products.models import Bundle, Product


class BundleListView(LoginRequiredMixin, MultipleObjectTemplateResponseMixin, BaseListView):
    """Get list of bundles"""
    model = Bundle
    filterset_class = BundleFilter
    template_name = 'products/bundle_list.html'
    success_url = reverse_lazy('products:bundle-list')

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user)
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        return context


class BundleCreateView(LoginRequiredMixin, CreateView):
    form_class = BundleCreateForm
    template_name = 'products/bundle_create.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(
            {'user': request.user}, request.POST
        )
        if form.is_valid():
            product = form.save()
            messages.success(self.request, f'Bundle "{product.name}" was successfully created')
            return HttpResponseRedirect(reverse('products:bundle-list'))

        return render(request, self.template_name, {'form': form})


class BundleDetailView(LoginRequiredMixin, DetailView):
    """Get specific bundle"""
    model = Bundle
    template_name = 'products/bundle_detail.html'
    context_object_name = 'bundle'
    success_url = reverse_lazy('products:bundle-detail')

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.kwargs['bundle_id'], user=self.request.user)


class BundleUpdateView(LoginRequiredMixin, UpdateView):
    form_class = BundleUpdateForm
    template_name = 'products/bundle_update.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Bundle, pk=self.kwargs['bundle_id'], user=self.request.user)

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        form = self.form_class(instance=product)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        bundle = self.get_object()
        form = self.form_class(
            {'user': request.user}, request.POST, request.FILES, instance=bundle
        )
        if form.is_valid():
            bundle = form.save()
            messages.success(self.request, f'Bundle "{bundle.name}" was successfully updated')
            return HttpResponseRedirect(reverse('products:bundle-detail', args=(bundle.id,)))

        return render(request, self.template_name, {'form': form})


class BundleDeleteView(LoginRequiredMixin, DeleteView):

    def get_object(self, queryset=None):
        return get_object_or_404(Bundle, pk=self.kwargs['bundle_id'], user=self.request.user)

    def post(self, request, *args, **kwargs):
        bundle = self.get_object()
        bundle.delete()
        messages.success(self.request, f'Object "{bundle.name}" was deleted')
        return HttpResponseRedirect(reverse('products:bundle-list'))


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'
    success_url = reverse_lazy('products:product-detail')

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.kwargs['product_id'], bundle__user=self.request.user)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'product': self.get_object()})


class ProductCreateView(LoginRequiredMixin, CreateView):
    form_class = ProductCreateForm
    template_name = 'products/product_create.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Bundle, pk=self.kwargs['bundle_id'], user=self.request.user)

    def get(self, request, *args, **kwargs):
        bundle = self.get_object()
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'bundle': bundle})

    def post(self, request, *args, **kwargs):
        form = self.form_class(
            {'bundle_id': kwargs.get('bundle_id'), 'user': request.user}, request.POST, request.FILES
        )
        if form.is_valid():
            product = form.save()
            messages.success(self.request, f'Successfully created "{product.name}"')
            return HttpResponseRedirect(reverse('products:bundle-detail', args=(kwargs.get('bundle_id'),)))

        return render(request, self.template_name, {'form': form})


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProductUpdateForm
    template_name = 'products/product_update.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Product, pk=self.kwargs['product_id'], bundle__user=self.request.user)

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        form = self.form_class(instance=product)
        return render(request, self.template_name, {'form': form, 'bundle': product.bundle})

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        form = self.form_class(
            {'user': request.user}, request.POST, request.FILES, instance=product
        )
        if form.is_valid():
            product = form.save()
            messages.success(self.request, f'Object "{product.name}" was successfully updated')
            return HttpResponseRedirect(reverse('products:bundle-detail', args=(product.bundle.id,)))

        return render(request, self.template_name, {'form': form})


class ProductDeleteView(LoginRequiredMixin, DeleteView):

    def get_object(self, queryset=None):
        return get_object_or_404(Product, pk=self.kwargs['product_id'], bundle__user=self.request.user)

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        product.delete()
        messages.success(self.request, f'Object "{product.name}" was deleted')
        return HttpResponseRedirect(reverse('products:bundle-detail', args=(product.bundle.id,)))

templates/products/bundle_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
      <legend class="border-bottom mb-4">Create bundle</legend>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Save</button>
      </div>
  </form>
{% endblock %}

templates/products/bundle_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="content-center m-5">
        <div>
            <div class="form-group row">
                <div>
                    <b>Bundle Name: </b>
                    {{ bundle.name }}
                </div>

                <a class="ml-2" href="{% url 'products:bundle-update' bundle.pk %}">
                    <button class="btn btn-sm btn-clean btn-icon btn-icon-md edit-action">
                        {% include 'icons/edit_icon.html' %}
                    </button>
                </a>
                <form action="{% url 'products:bundle-delete' bundle.id %}" method="post" style="display: inline;" class="ml-2">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-clean btn-icon btn-icon-md delete-action" type="submit" onclick="return confirm('Are you sure you want to delete whole bundle {{ bundle.name }}?')">
                        {% include 'icons/trash_icon.html' %}
                    </button>
                </form>

            </div>

            <div class="form-group mt-5">
                {% for product in bundle.products.all %}
                    <div class="container" style="width: 100%">
                        <div class="row mb-4" style="justify-content: space-between">
                            <div>
                                <a href="{% url 'products:product-detail' product.id %}">
                                    <h5>
                                        {{ product.name }}
                                    </h5>
                                </a>
                            </div>

                            <div class="row">
                                <div class="ml-2">
                                    <a href="{% url 'products:product-update' product.id %}">
                                        <button class="btn btn-secondary" type="submit">Edit</button>
                                    </a>
                                </div>
                                <form action="{% url 'products:product-delete' product.id %}" method="post" style="display: inline;" class="ml-2">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure you want to delete this object?')">Delete</button>
                                </form>
                            </div>
                        </div>

                    </div>


                {% endfor %}
            </div>

            <div class="form-group">
                <a href="{% url 'products:product-create' bundle.id %}">
                    <button class="btn btn-outline-info" type="submit">Add object</button>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/products/bundle_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="content-center">
        <div class="main container-fluid padding">
            <div style="margin-bottom: 30px;justify-content: space-between" class="row">
                <div>
                    <form method="get">
                        <input type="text" name="search" id="id_search" placeholder="Search" value="{{ filterset.form.search.value|default:'' }}">
                        {{ filterset.form.ordering }}
                        <input type="submit" />
                    </form>
                </div>
                <div class="form-group">
                    <a href="{% url 'products:bundle-create' %}">
                        <button class="btn btn-outline-info" type="submit">Create bundle</button>
                    </a>
                </div>
            </div>
            <div style="display: flex;flex-wrap: wrap;padding: 0" class="col-8">
                {% for bundle in bundle_list %}
                    <div style="" class="col-4">
                        <a href="{% url 'products:bundle-detail' bundle.id %}">
                            <img src="{% static 'images/folder_1.png' %}" width="200" height="200px" alt="">
                            <hr>
                            <h4>
                                {{ bundle.name }}
                            </h4>
                        </a>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/products/bundle_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
      <legend class="border-bottom mb-4">Update Bundle</legend>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Save</button>
      </div>
  </form>
{% endblock %}

templates/products/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
      <legend class="border-bottom mb-4">Create object for bundle <b>{{ bundle.name }}</b></legend>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Save</button>
      </div>
  </form>
{% endblock %}

templates/products/product_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-4">
        <div class="card">
          {% if product.image %}
            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }} Photo">
          {% endif %}

          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
          </div>
        </div>
      </div>
      <div class="col-md-6 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Object Asset</h5>
            {% if product.asset %}
              <p><a href="{{ product.asset.url }}">{{ product.asset.name }}</a></p>
            {% else %}
              <p>No file available</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/products/product_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
      <legend class="border-bottom mb-4">Update object</legend>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Save</button>
      </div>
  </form>
{% endblock %}