authentication/urls.py
from django.urls import path
from authentication import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate-account/', views.ActivateAccountView.as_view(), name='activate-account'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('bundles/', views.BundleListView.as_view(), name='bundle-list'),
    path('bundles/create/', views.BundleCreateView.as_view(), name='bundle-create'),
    path('bundles/<int:bundle_id>/', views.BundleDetailView.as_view(), name='bundle-detail'),
    path('bundles/<int:bundle_id>/update/', views.BundleUpdateView.as_view(), name='bundle-update'),
    path('bundles/<int:bundle_id>/delete/', views.BundleDeleteView.as_view(), name='bundle-delete'),

    path('bundles/<int:bundle_id>/products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<int:product_id>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/<int:product_id>/update/', views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<int:product_id>/', views.ProductDetailView.as_view(), name='product-detail'),
    # path('bundles/create/', views.BundleListView.as_view(), name='bundle-create'),
    # path('bundles/<int:bundle_id>/update/', views.BundleListView.as_view(), name='bundle-update'),
    # path('bundles/<int:bundle_id>/delete/', views.BundleListView.as_view(), name='bundle-delete'),
]

project_3d/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from common import views as common_views

urlpatterns = [
    path('', common_views.redirect_home, name='root'),
    path('home/', common_views.HomeView.as_view(), name='home'),
    path('documentation/', common_views.DocumentationView.as_view(), name='documentation'),

    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('products.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="{% static 'favicon1.jpg' %}" type="image/png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% block links %}
    {% endblock links %}

    {% if title %}
        <title>Project 3D - {{ title }}</title>
    {% else %}
        <title>Project 3D</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Project 3D</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'documentation' %}">Documentation</a>
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'products:bundle-list' %}">My bundles</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <p class="nav-item nav-link remove-hover">{{ user.email }}</p>
                <a class="nav-item nav-link" href="{% url 'auth:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'auth:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'auth:login' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div role="main" class="container">
      <div class="row">
        <div class="col-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/documentation.html
{% extends 'base.html' %}
{% block content %}
    <div>Now you look at <b>Documentation</b></div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div>Now you look at <b>Home page</b></div>
{% endblock content %}